"""create incident evidence links

Revision ID: 38e63a81a38e
Revises: a2cf06d485ad
Create Date: 2026-09-10 17:09:27.589897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from orinfra_sentinelops.infrastructure.persistence.types import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "38e63a81a38e"
down_revision: str | Sequence[str] | None = "a2cf06d485ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_evidence_links",
        sa.Column("incident_id", sa.String(length=100), nullable=False),
        sa.Column("evidence_id", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("linked_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.evidence_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.incident_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_evidence_links")
    # ### end Alembic commands ###
